  #ansible-playbook ./playbooks/password-change.yml --user someuser --ask-become-pass -i ./inventory/hosts --extra-vars newpassword=P@ssword!!(replace)
  - name: password change
    hosts: "*"
    become: true
    tasks:
    - name: change user's password
      user:
        name: someuser
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"


