---
name: 'Pull Request'
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
jobs:
  lint-eveything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3